#! /bin/bash

# This was made due to an unresolved error in the 'collect_data.py' file.

while true; 
do 
    python collect_data_catered.py; 
done
